CREATE DATABASE IF NOT EXISTS Car_Center;


CREATE USER IF NOT EXISTS 'joker'@'localhost' IDENTIFIED BY 'etudiants_1';
GRANT ALL ON Car_Center.* TO 'joker'@'localhost';

 
 
use Car_Center;



CREATE TABLE IF NOT EXISTS SERVICES_OFFERED (
  services INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
  );
  
CREATE TABLE IF NOT EXISTS MARKS (
  mark INT AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY(mark)
  );
  
CREATE TABLE IF NOT EXISTS MODELS (
   model INT AUTO_INCREMENT,
   name VARCHAR(30) NOT NULL,
   PRIMARY KEY(mark)
   );
   
CREATE TABLE IF NOT EXISTS ORIGINS (
    origin INT AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    PRIMARY KEY(origin)
    );
    
CREATE TABLE IF NOT EXISTS COLOURS (
   colour INT AUTO_INCREMENT,
   name VARCHAR(30) NOT NULL,
   PRIMARY KEY(colour)
   );
   
CREATE TABLE IF NOT EXISTS YEARS (
  year INT  AUTO_INCREMENT,
  name INT NOT NULL,
  PRIMARY KEY(year)
  );

CREATE TABLE IF NOT EXISTS ENGIN_TYPES (
  engin_type INT AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY(engin_type)
  );

CREATE TABLE IF NOT EXISTS PRICES (
  price INT AUTO_INCREMENT,
  name INT NOT NULL,
  PRIMARY KEY(price)
  );

CREATE TABLE IF NOT EXISTS MAINTENANCES (
  maintenance INT AUTO_INCREMENTS,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY(maintenance)
  );
  
  
