-- Dans le domaine

use Car_Center;

-- Données des tables

INSERT INTO SERVICES_OFFERED (Sale) VALUES ('SUV');
INSERT INTO SERVICES_OFFERED (Sale) VALUES ('Truck');
INSERT INTO SERVICES_OFFERED (Sale) VALUES ( 'Sport_Car');

INSERT INTO MARKS (Marks) VALUES ('JEEP');
INSERT INTO MARKS (Marks) VALUES ('Acura');
INSERT INTO MARKS (Marks) VALUES ('Lamborghini');

INSERT INTO MODELS (Models, origin) VALUES ('WRANGLER');
INSERT INTO MODELS (Models, origin) VALUES (AVENTADOR);
INSERT INTO MODELS (Models, origin) VALUES ('NSX');

INSERT INTO ORIGINS (Origins, mark) VALUES ('USA');
INSERT INTO ORIGINS (Origins, mark) VALUES ('ITALY');
INSERT INTO ORIGINS (Origins, mark) VALUES ('JAPAN');

INSERT INTO COLOURS (Colours) VALUES ('Black');
INSERT INTO COLOURS (Colours) VALUES ('BLUEU');
INSERT INTO COLOURS (Colours) VALUES ('GRAY');
INSERT INTO COLOURS (Colours) VALUES ('WHITE');
INSERT INTO COLOURS (Colours) VALUES ('GREEN');

INSERT INTO YEARS (Years, model) VALUES ('2019-02-20');
INSERT INTO YEARS (Years, model) VALUES ('2015-11-09');
INSERT INTO YEARS (Years, model) VALUES ('2019-01-03');

INSERT INTO ENGIN_TYPES (Engins) VALUES ('Hybrid');
INSERT INTO ENGIN_TYPES (Engins) VALUES ('Electric');
INSERT INTO ENGIN_TYPES (Engins) VALUES ('Petrol');

INSERT INTO PRICES (model) VALUES (43000);
INSERT INTO PRICES (model) VALUES (43000);
INSERT INTO PRICES (model) VALUES (43000);

INSERT INTO MAINTENANCES (Maintenances) VALUES ('Transmission');
INSERT INTO MAINTENANCES (Maintenances) VALUES ('Brake');
INSERT INTO MAINTENANCES (Maintenances) VALUES ('Tires');
INSERT INTO MAINTENANCES (Maintenances) VALUES ('Repair');

